# Use root/example as user/password credentials
version: '3.1'
services:

  db:
    container_name: mysql
    image: mysql:5.7
    ports: 
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: "311332065"
      MYSQL_USER: "root"
    volumes:
      - "/home/danterangelrobles/Documentos/Data/MySQL:/var/lib/mysql"